apiVersion: 1

datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: ${GF_DATASOURCE_LOKI_URL}
    isDefault: false
    editable: true
    allowUiUpdates: true
    jsonData:
      maxLines: 1000
      timeout: 60
