apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://oullin_prometheus_local:9090
    isDefault: true
    editable: true
    allowUiUpdates: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
